In [145]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPClassifier
import numpy as np
import pandas as pd
import os



SyntaxError: invalid syntax (<ipython-input-145-71d1028615f2>, line 8)

In [66]:
os.chdir(r'..\ese-417-final-project\data\preprocessed')
X = np.load('X_array.npy')
y = np.load('y_array.npy')

In [67]:
y

array([5, 5, 5, ..., 6, 5, 6], dtype=int64)

In [68]:
X

array([[-0.52443096,  0.93200015, -1.39325797, ...,  1.29187216,
        -0.57856134, -0.95437429],
       [-0.29406274,  1.91580043, -1.39325797, ..., -0.70839548,
         0.12482157, -0.5845748 ],
       [-0.29406274,  1.25993358, -1.18861732, ..., -0.32124691,
        -0.05102416, -0.5845748 ],
       ...,
       [-1.38831178,  0.11216658, -0.88165635, ...,  1.35639693,
         0.59374351,  0.7097234 ],
       [-1.38831178,  0.63139451, -0.77933603, ...,  1.67902074,
         0.3006673 , -0.21477532],
       [-1.33071973, -1.19956712,  1.01126962, ...,  0.51757501,
         0.00759108,  0.52482366]])

In [69]:
X_train = np.load('X_train.npy')
y_train = np.load('y_train.npy')
X_test = np.load('X_test.npy')
y_test = np.load('y_test.npy')


## solver activation num layer

In [88]:
from sklearn.model_selection import GridSearchCV
model_ann = MLPClassifier(max_iter = 800)
param_grid = {
                'solver': ['sgd','lbfgs','adam'],
                'activation':['logistic','tanh','relu'],
                'hidden_layer_sizes':[(i,i)for i in range(5,300,5)],
                'alpha' : [0.01],
                'learning_rate_init': [0.1],
}

gs = GridSearchCV(model_ann,param_grid,n_jobs = -1,cv = 2)
gs_result = gs.fit(X_train,y_train)

In [219]:
gs_result.best_score_

0.5917350437227937

In [220]:
gs_result.best_params_

{'activation': 'logistic',
 'alpha': 0.01,
 'hidden_layer_sizes': (110, 110),
 'learning_rate_init': 0.1,
 'solver': 'sgd'}

In [221]:
import joblib
gs_result.best_estimator_


MLPClassifier(activation='logistic', alpha=0.01, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(110, 110), learning_rate='constant',
              learning_rate_init=0.1, max_fun=15000, max_iter=800, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=None, shuffle=True, solver='sgd', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [222]:
os.chdir(r'..\ese-417-final-project')
joblib.dump(gs_result.best_estimator_, 'models/best_ann_grid_search.pkl', compress = 1)
joblib.dump(gs_result, 'models/ann_grid_search.pkl', compress = 1)

['models/ann_grid_search.pkl']

In [223]:
##
MLP = MLPClassifier(activation = 'logistic', 
                       solver = 'sgd', 
                       hidden_layer_sizes = (110,110), 
                       alpha=0.01, 
                       max_iter = 800,
                       learning_rate_init = 0.1)
MLP_result = MLP.fit(X_train,y_train)

In [224]:
from sklearn.metrics import confusion_matrix
from utils.ut import evaluate_by_accuracy

accuracy = evaluate_by_accuracy(MLP_result, X_test, y_test)
y_true = y_test
y_predict = MLP_result.predict(X_test)


Confusion_matrix = confusion_matrix(y_true,y_predict)
Confusion_matrix


Model Performance
Average Error: 0.4294 degrees.
Accuracy = 92.43%.


array([[  0,   1,   0,   0,   0,   0],
       [  0,   0,   7,   2,   1,   0],
       [  0,   0, 106,  25,   1,   0],
       [  0,   0,  56,  76,  17,   0],
       [  0,   0,   2,  21,  20,   0],
       [  0,   0,   0,   1,   4,   0]], dtype=int64)

In [225]:
joblib.dump(Confusion_matrix, 'models/ann_confusionz_matrix.pkl', compress = 1)
joblib.dump(accuracy, 'models/ann_accuracy.pkl', compress = 1)
joblib.dump(y_predict, 'models/ann_predict.pkl', compress = 1)

['models/ann_predict.pkl']