In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPClassifier
import numpy as np
import pandas as pd
import os



In [2]:
os.chdir(r'C:\Users\qingyuan.1016\myJupyter\ese-417-final-project\data\preprocessed')
X = np.load('X_array.npy')
y = np.load('y_array.npy')

In [3]:
y

array([5, 5, 5, ..., 6, 5, 6], dtype=int64)

In [4]:
X

array([[-0.52443096,  0.93200015, -1.39325797, ...,  1.29187216,
        -0.57856134, -0.95437429],
       [-0.29406274,  1.91580043, -1.39325797, ..., -0.70839548,
         0.12482157, -0.5845748 ],
       [-0.29406274,  1.25993358, -1.18861732, ..., -0.32124691,
        -0.05102416, -0.5845748 ],
       ...,
       [-1.38831178,  0.11216658, -0.88165635, ...,  1.35639693,
         0.59374351,  0.7097234 ],
       [-1.38831178,  0.63139451, -0.77933603, ...,  1.67902074,
         0.3006673 , -0.21477532],
       [-1.33071973, -1.19956712,  1.01126962, ...,  0.51757501,
         0.00759108,  0.52482366]])

In [5]:

os.chdir(r'C:\Users\qingyuan.1016\myJupyter\ese-417-final-project')
from sklearn.metrics import confusion_matrix
from utils.ut import load_data
#accuracy = evaluate_by_accuracy(MLP_result, X_test, y_test)
X_train, X_test, y_train, y_test = load_data(4)

#y_train.shape

In [6]:
#X_train = np.load('X_train.npy')
#y_train = np.load('y_train.npy')
#X_test = np.load('X_test.npy')
#y_test = np.load('y_test.npy')
##backup parameter
#'solver': ['sgd','lbfgs','adam'],
#                'activation':['logistic','relu','tanh'],
#               'hidden_layer_sizes':[(15,15),(15,),(120,),(120,120),(100,100),(100,)],
#                'learning_rate_init':[0.1,0.5],
#                'max_iter':[150,200],
#                'momentum':[0.9,0.5,0.1],
#               'batch_size':['auto'],

## after determining the best paremeter, starting to find the best hidden layer size

In [10]:
from sklearn.model_selection import GridSearchCV
import warnings
from sklearn.exceptions import ConvergenceWarning

with warnings.catch_warnings():
    warnings.simplefilter("ignore", category=ConvergenceWarning)
    model_ann = MLPClassifier(random_state=20)

    param_grid = {
                'solver': ['sgd'],
                'activation':['relu'],
                'hidden_layer_sizes':[(i,i)for i in range(5,300,5)],
                'learning_rate_init':[0.1],
                'max_iter':[200],
                'momentum':[0.9],
                'batch_size':['auto'],
  
  
               
    }

    gs = GridSearchCV(model_ann,param_grid,n_jobs = 1,cv = 3)
    gs_result = gs.fit(X_train,y_train)

In [11]:
gs_result.best_score_

0.9388379204892966

In [12]:
gs_result.best_params_

{'activation': 'relu',
 'batch_size': 'auto',
 'hidden_layer_sizes': (275, 275),
 'learning_rate_init': 0.1,
 'max_iter': 200,
 'momentum': 0.9,
 'solver': 'sgd'}

In [13]:
import joblib
gs_result.best_estimator_


MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(275, 275), learning_rate='constant',
              learning_rate_init=0.1, max_fun=15000, max_iter=200, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=20, shuffle=True, solver='sgd', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)

In [14]:
os.chdir(r'C:\Users\qingyuan.1016\myJupyter\ese-417-final-project')
joblib.dump(gs_result.best_estimator_, 'models/best_ann_grid_search.pkl', compress = 1)
joblib.dump(gs_result, 'models/ann_grid_search.pkl', compress = 1)

['models/ann_grid_search.pkl']

In [15]:
MLP = MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
                      beta_2=0.999, early_stopping=False, epsilon=1e-08,
                      hidden_layer_sizes=(275,275 ), learning_rate='constant',
                      learning_rate_init=0.1, max_fun=15000, max_iter=200, momentum=0.9,
                      n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
                      random_state=20, shuffle=True, solver='sgd', tol=0.0001,
                      validation_fraction=0.1, verbose=False, warm_start=False)
MLP_result = MLP.fit(X_train,y_train)

In [16]:
##
"""
MLP = MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
              beta_2=0.999, early_stopping=False, epsilon=1e-08,
              hidden_layer_sizes=(120,120 ), learning_rate='constant',
              learning_rate_init=0.1, max_fun=15000, max_iter=200, momentum=0.9,
              n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
              random_state=20, shuffle=True, solver='sgd', tol=0.0001,
              validation_fraction=0.1, verbose=False, warm_start=False)
"""
from sklearn.metrics import accuracy_score
import joblib
from sklearn.metrics import confusion_matrix
from utils.ut import load_data
os.chdir(r'C:\Users\qingyuan.1016\myJupyter\ese-417-final-project')
accuracy_score_ann = []

def ann_performance_score():
    
    for i in range(11):
       

        #accuracy = evaluate_by_accuracy(MLP_result, X_test, y_test)
        X_train, X_test, y_train, y_test = load_data(i)

        y_train.shape
        MLP = MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
                      beta_2=0.999, early_stopping=False, epsilon=1e-08,
                      hidden_layer_sizes=(275,275 ), learning_rate='constant',
                      learning_rate_init=0.1, max_fun=15000, max_iter=200, momentum=0.9,
                      n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
                      random_state=20, shuffle=True, solver='sgd', tol=0.0001,
                      validation_fraction=0.1, verbose=False, warm_start=False)
        MLP_result = MLP.fit(X_train,y_train)
       
        joblib.dump(MLP_result, 'models/ann_%d.pkl'%(i), compress = 1)
        y_true = y_test
        y_predict = MLP_result.predict(X_test)
       
        accuracy = accuracy_score(y_true, y_predict)

        accuracy_score_ann.append(accuracy)
    np.save('models/ann_performance_score.npy', accuracy_score_ann)

In [18]:
ann_performance_score()

In [19]:
#from sklearn.metrics import confusion_matrix
#from utils.ut import evaluate_by_accuracy
from sklearn.metrics import accuracy_score

#accuracy = evaluate_by_accuracy(MLP_result, X_test, y_test)
y_true = y_test
y_predict = MLP_result.predict(X_test)
accuracy = accuracy_score(y_true, y_predict)
accuracy



0.8525

In [20]:
accuracy_score_ann

[0.87,
 0.85,
 0.85,
 0.84,
 0.835,
 0.8425,
 0.825,
 0.7775,
 0.72,
 0.6,
 0.6125,
 0.87,
 0.85,
 0.85,
 0.84,
 0.835,
 0.8425,
 0.825,
 0.7775,
 0.72,
 0.6,
 0.6125]

In [21]:
Confusion_matrix = confusion_matrix(y_true,y_predict)
Confusion_matrix


array([[  2,  11,   0],
       [ 12, 299,  16],
       [  1,  19,  40]], dtype=int64)

In [22]:
import joblib
joblib.dump(Confusion_matrix, 'models/ann_confusionz_matrix.pkl', compress = 1)
joblib.dump(accuracy, 'models/ann_accuracy.pkl', compress = 1)
joblib.dump(y_predict, 'models/ann_predict.pkl', compress = 1)

['models/ann_predict.pkl']